### ISSUE TITLE
PHP Warning:  trim() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by slaFFik** [xwp/stream#883] opened 2016-09-29 10:54 UTC
> [29-Sep-2016 10:48:39 UTC] PHP Warning:  trim() expects parameter 1 to be string, array given in /home/user/u/www.domain.com/app/plugins/stream/classes/class-settings.php on line 87

It repeated 7 times in a row in my error log. Seconds were a bit different.

Link: https://github.com/xwp/stream/blob/develop/classes/class-settings.php#L87

Stream 3.0.7, WordPress 4.6.1

**Comment by lukecarbis** [comment] 2016-10-11 04:41
Thanks @slaFFik - that's interesting. Must be caused by a form passing an array... I'll try to replicate it and track it down.

**Comment by lukecarbis** [comment] 2016-11-01 06:35
Closing in favour of #888

**Closed by lukecarbis** 2016-11-01 06:35 UTC
