### ISSUE TITLE
Stream 2 to Stream 3 update inconsistencies

### ISSUE THREAD

**Issue by MarioKnight** [xwp/stream#734] opened 2015-08-25 13:31 UTC
I am currently updating clients' sites one by one who have Stream 2 active.  Some have gone through with no issues, but I have noticed a couple of oddities.

* On every occasion updating through the dashboard, the update just sort of stops after "Disabling Maintenance mode…" is displayed.  There is no message of the update being complete, which displays an update being available for the next click or two before the flag is removed by itself.

* On some occasions after the "Disabling Maintenance mode…" message, the following error is given: `Fatal error: Class 'WP_Stream_Author' not found in /home/xxxx/public_html/wp-content/plugins/stream/classes/class-wp-stream-log.php on line 69`, possibly related to https://github.com/xwp/stream/issues/729 ?

* Some sites will still convert fine after this.  One site is currently stuck at 100%, and another site doesn't even show the percentage bar.  Both have remained open for nearly half an hour as I type this.

I'm not sure how I can further troubleshoot, however please let me know how I can obtain more information if needed to help resolve these issues.  Thank you.

**Comment by sirjonathan** [comment] 2015-08-25 13:55
@MarioKnight - Luke, the lead developer, will be online later today and will follow-up in detail. Till then, the first thought that comes to mind is the hosting environment - What host (or hosts) are you using for your client sites?

**Comment by MarioKnight** [comment] 2015-08-25 14:30
We use dedicated servers running cPanel/WHM which I have root access to.  The sites that show these issues have PHP 5.4.43 running.  There is also a server with PHP 5.6.11 running, however the one active Stream installation on that server converted with no issues.

Between my messages in this thread, I have discovered that the site that fails to show the percentage bar has additional error messages when I update other plugins:

`Warning: Illegal string offset 'connector' in /home/xxxx/public_html/wp-content/plugins/stream/connectors/class-connector-woocommerce.php on line 611`

`Warning: Illegal string offset 'connector' in /home/xxxx/public_html/wp-content/plugins/stream/connectors/class-connector-woocommerce.php on line 613`

`Warning: Illegal string offset 'connector' in /home/xxxx/public_html/wp-content/plugins/stream/connectors/class-connector-woocommerce.php on line 615`

The above messages loop a number of times, though don't appear to affect the update process.

**Comment by lukecarbis** [comment] 2015-08-25 22:43
@MarioKnight I'm closing this ticket because I believe it's a duplicate of #729. The woocommerce connector issue is unrelated, I'll create a separate ticket for that.

**Closed by lukecarbis** 2015-08-25 22:43 UTC
