### ISSUE TITLE
Database error when comment has been approved by super admin

### ISSUE THREAD

**Issue by mundschenk-at** [xwp/stream#807] opened 2015-12-11 18:50 UTC
I get a slew of database errors regarding the column `user_role`, e.g. when approving a comment. I assume this happens because the user is a super admin.

```WordPress database error Column 'user_role' cannot be null for query INSERT INTO `<prefix>_stream```

**Comment by lukecarbis** [comment] 2015-12-18 00:00
Hi @mundschenk-at . I've tried testing this but can't reproduce. I've been testing on multisite as a Super Admin. I've tried being added as a User to the site, and without being added as a User.

Either way, no database errors.

Could you give me steps to reproduce? Also, is this a new-ish install of Stream 3, or have you been a long time user?

**Comment by mundschenk-at** [comment] 2015-12-18 08:42
I've been using Stream since the initial release of Stream 3, but not before. Maybe we should compare the schema dumps? Is the column supposed to be nullable or not?

**Comment by lukecarbis** [comment] 2015-12-21 03:14
My database schema says that `user_role` doesn't accept `null` values (so it _is not_ nullable).

However, it should accept empty strings (which Stream does sometimes: in the case of the N/A user like a cron or cli).

**Comment by mundschenk-at** [comment] 2015-12-21 08:40
If it is not nullable, then the schema and the database itself are not at fault. The problem appears when triggering a plugin update on Multisite. The resulting entry has the Summary "Updated plugin:" (without the plugin name!), User "N/A", Context "Installer -> Plugins", Action "Updated", Site and IP Address normal.

**Comment by lukecarbis** [comment] 2015-12-29 00:40
I've been able to replicate the "Update plugin:" (no plugin name) error. This occurs when the plugin is updated via AJAX from the plugins list table.

However, I've been unable to replicate with the User "N/A". Each time it has the correct user. What's more, I don't receive any errors.

When logged in as the primary super admin, my database shows a `user_role` of `administrator`. This may be because the user has sites assigned to it. When logged in as a test super admin, the database (correctly) shows a `user_role` of "" (an empty string). My guess is that this is because there are no sites assigned to this test user.

Can you please take a look at your schema, and compare it to mine?

<img width="1250" alt="screen shot 2015-12-29 at 10 38 56" src="https://cloud.githubusercontent.com/assets/1097667/12027805/71acbd12-ae18-11e5-9340-15c292f12a86.png">

**Comment by mundschenk-at** [comment] 2015-12-31 10:42
Sorry for the late reply. The schema looks identical. The superuser acount in my setup also has (some) sites assigned to it. However, for admin actions on the network level, I don't think the "administrator" role is ever valid (even though some parts of WP core sometimes think they are doing things on the primary site, strictly speaking, that is not true).

**Comment by mundschenk-at** [comment] 2015-12-31 15:34
I just updated a plugin and this time the user and plugin name were recorded correctly. This was a single update, not from the list view.

**Comment by lukecarbis** [comment] 2016-03-01 01:50
@chacha Could you have a look at the AJAX Plugin update error? If you can replicate the N/A user issue, then feel free to look into that too. If not, I'm happy to close this issue without that fix since we can't replicate it.

**Comment by lukecarbis** [comment] 2016-03-01 01:51
Also, might be worth attempting to update multiple plugins at once.

**Comment by lukecarbis** [comment] 2016-03-17 21:40
@mundschenk-at This may be fixed in bugfix/issue-829. Could you please check out that branch and see if you still get the error?

**Comment by mundschenk-at** [comment] 2016-03-17 22:52
I'll have a look at it on the weekend.

**Comment by lukecarbis** [comment] 2016-03-29 01:39
@mundschenk-at Any update?

**Comment by mundschenk-at** [comment] 2016-03-29 05:40
Sorry, didn't get around to it yet. I'll try tonight.

**Comment by mundschenk-at** [comment] 2016-03-29 18:43
The error hasn't occured "in the wild" since March 1st, according to my logfiles. Since I'm unable to trigger it, the bug seems to have been fixed in 3.0.5 (I couldn't find the branch `bugfix/issue-829` so I assume it has been merged already?).

**Comment by mundschenk-at** [comment] 2016-03-29 18:46
BTW: I just noticed we were potentially talking about different things here. Did you mean for me to check out the database error or the "user N/A" thing when updating?

**Comment by lukecarbis** [comment] 2016-03-29 20:42
Yes, it's been merged. I was meaning both.

If the issue has been resolved for you, please consider leaving Stream a review: https://wordpress.org/support/view/plugin-reviews/stream?filter=5#postform

**Comment by mundschenk-at** [comment] 2016-04-06 08:29
Yes, it looks like the original issues has been resolved. Something similar is happening with the push-to-deploy feature of WP Pusher, though. I'll create new issue once I've had time to investigate this a bit more.

**Comment by chacha** [comment] 2016-05-30 23:15
It looks like this issue has been resolved. I'm going to close. Please reopen if I am mistaken.

**Closed by chacha** 2016-05-30 23:15 UTC
